version: '3.2'

services:
  elasticsearch:
    build:
      context: "${PWD}/elasticsearch/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "${PWD}/elasticsearch/config/elasticsearch.yml"
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - "${PWD}/elasticsearch/data:/var/lib/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
    networks:
      - elk

  flutend:
    build:
      context: "${PWD}/fluentd/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "${PWD}/fluentd/conf/fluentd.conf"
        target: /usr/share/fluentd/conf/fluentd.conf
        read_only: true
    ports:
      - "24224:24224"
    networks:
      - default
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: "${PWD}/kibana/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "${PWD}/kibana/config/kibana.yml"
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
